import { FileActionName, FileActionStatus } from './file.action.enums';
//relation file 1:m FileActions
export class FileActionEntity {
    id?: number; //PK - managed in DB as autogenerated
    name: FileActionName; //UPLOAD, IMPORT, CLEAR-UPLOADS
    status: FileActionStatus; // ACTIVE, INACTIVE
    updatedOn?: Date; //triggered on action
    updatedBy: number; //FK user id

    constructor() {
        this.name = FileActionName.UPLOAD; //default action
        this.status = FileActionStatus.ACTIVE; //default status
        this.updatedBy = 1; //default user
        this.updatedOn = new Date(); //default to now
    }
}
