export const DB_STRATEGY = Symbol('DB_STRATEGY');
export const DB_FACTORY = Symbol('DB_FACTORY');

export const PERSON_REPOSITORY = Symbol('PERSON_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const AUTH_REPOSITORY = Symbol('AUTH_REPOSITORY');

export const FILE_ACTION_REPOSITORY = Symbol('FILE_ACTION_REPOSITORY');
export const FILE_TO_ACTION_REPOSITORY = Symbol('FILE_TO_ACTION_REPOSITORY');
export const FILE_DETAIL_TYPE_REPOSITORY = Symbol('FILE_DETAIL_TYPE_REPOSITORY');
export const FILE_DETAIL_REPOSITORY = Symbol('FILE_DETAIL_REPOSITORY');
